### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by ForeverButthurt** [zerothefallen/Quack-Anti-Cheat#11]
Player [8][RubinXD] ERR: addons/qac/lua/autorun/client/!!_cl_qac.lua:108: bad argument #1 to 'ofunc' (number expected, got nil)

I don't know how this happens but sometimes i see this error in server console.

**Comment by zerothefallen** [comment]
You have a conflicting add-on. This anti-cheat is no longer supported. Please do not open issues about it.
