### ISSUE TITLE
Config changes not applying?

### ISSUE THREAD

**Issue by thelmexx** [zerothefallen/Quack-Anti-Cheat#9]
When I go into the config file for QAC and make changes, it doesnt apply the changes, even after a server restart.

Config file is in the right place (QAC/lua/autorun/server/!!_sv_qac.lua)
No LUA Errors in console or clientside
Attempted renaming from !!_sv_qac.lua to sv_qac.lua, no results

EDIT: After further testing, it appears that the functions that handle banning and displaying to admins are broken. Only playing the sound effect and printing to console works.

**Comment by zerothefallen** [comment]
QAC is no longer updated, but should still work regardless. I rewrote banning logic so there is a possibility the config no longer works. Sorry, but I cannot help you.
